name=modulino_led-matrix_alt-library
version=1.0
author=arjun
maintainer=arjun <ay3020@nyu.edu>
sentence=alternative library for controlling the arduino modulino led-matrix.
paragraph=alternative library for controlling the arduino modulino led-matrix.
category=display
url=https://github.com/arjunmakesthings/modulino_led-matrix_alt-library
architectures=*
includes=points.h, font.h

